node {
     stages {
        stage('SCM') {
            git 'https://github.com/shanthilakshmi/Test_JenkinsPipeline.git'
         }
    stage('clean') {
        sh label: '', script: 'dotnet clean'
    }
    stage('compile test package') {
        sh label: '', script: 'dotnet run'
    }
        stage( 'publish' ){
          sh lable: '', script: 'dotnet publish'
       }
    }
}
